In [1]:
import tensorflow as tf
import os

# Load the saved model
imported = tf.saved_model.load("saved")

In [2]:
test1 = tf.io.read_file("New_Test/Sound_Drum/100bpm-808-like-drum-loop-74838.wav")
waveform1, _ = tf.audio.decode_wav(test1, desired_channels=1, desired_samples=1600000)
waveform1 = tf.squeeze(waveform1, axis=-1)
# Add batch dimension
output1 = imported(tf.expand_dims(waveform1, 0)) 

print(output1)

{'predictions': <tf.Tensor: shape=(1, 4), dtype=float32, numpy=
array([[ 26.047459 , -29.991695 ,   1.4758577, -15.930263 ]],
      dtype=float32)>, 'class_ids': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([0], dtype=int64)>, 'class_names': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'Sound_Drum'], dtype=object)>}


In [3]:
test2 = tf.io.read_file("New_Test/Sound_Violin/Sad-Violin-H-www.fesliyanstudios.com.wav")
waveform2, _ = tf.audio.decode_wav(test2, desired_channels=1, desired_samples=1600000)
waveform2 = tf.squeeze(waveform2, axis=-1)
# Add batch dimension
output2 = imported(tf.expand_dims(waveform2, 0))  

print(output2)

{'predictions': <tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[ 2.030481 , -7.936515 ,  2.0641294,  2.4583647]], dtype=float32)>, 'class_ids': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([3], dtype=int64)>, 'class_names': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'Sound_Violin'], dtype=object)>}


In [4]:
test3 = tf.io.read_file("New_Test/Sound_Guiatr/rock_2_100BPM.wav")
waveform3, _ = tf.audio.decode_wav(test3, desired_channels=1, desired_samples=1600000)
waveform3 = tf.squeeze(waveform3, axis=-1)
# Add batch dimension
output3 = imported(tf.expand_dims(waveform3, 0))  

print(output3)

{'predictions': <tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[-2.912892 , 11.377988 , -5.1343093, -8.177461 ]], dtype=float32)>, 'class_ids': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1], dtype=int64)>, 'class_names': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'Sound_Guitar'], dtype=object)>}


In [5]:
test4 = tf.io.read_file("New_Test/Sound_Piano/ROOM-room8-MUS-chords.wav")
waveform4, _ = tf.audio.decode_wav(test4, desired_channels=1, desired_samples=1600000)
waveform4 = tf.squeeze(waveform4, axis=-1)
# Add batch dimension
output4 = imported(tf.expand_dims(waveform4, 0)) 

print(output4)

{'predictions': <tf.Tensor: shape=(1, 4), dtype=float32, numpy=
array([[-1.3494622 , -0.28962806,  1.6850353 , -1.7057853 ]],
      dtype=float32)>, 'class_ids': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([2], dtype=int64)>, 'class_names': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'Sound_Piano'], dtype=object)>}
